site_name: Playground Project
site_url: https://example.com
nav:
  - Home: index.md
  - Api Reference: api.md
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
markdown_extensions:
  - markdown_include.include:
      base_path: .
