site_name: magicli
site_url: https://example.com
nav:
  - Getting started: index.md
  - Examples: examples.md
  - Api Reference: api.md
theme:
  name: material
  logo: img/icon.svg
  favicon: img/icon.svg
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
  # name: readthedocs
  # highlightjs: true
# extra_css:
#   - style.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences